export const LOGIN = 'LOGIN'
export const LOGIN_PENDING = 'LOGIN_PENDING'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'
export const LOGOUT = 'LOGOUT'
export const LOGOUT_PENDING = 'LOGOUT_PENDING'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
export const TOKEN_AUTH_FAILURE = 'TOKEN_AUTH_FAILURE'

export const GET_USER_INFO = 'GET_USER_INFO'

export const REFRESH_DEMOPAGE = 'REFRESH_DEMOPAGE'
export const GETDATA_DEMOPAGE = 'GETDATA_DEMOPAGE'

export const ALREADY_SHOW = 'ALREADY_SHOW'

